[project]
name = "ironside"
version = "0.1.0"
dependencies = [
  "intelhex",
  "pyelftools",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
ironside = "ironside.__main__:main"

[tool.hatch.build.targets.wheel]
packages = ["ironside"]
